name: Daily Tech Podcast

on:
  schedule:
    # 6:00 AM IST = 00:30 UTC
    - cron: "30 0 * * *"
  workflow_dispatch:

jobs:
  run-podcast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run podcast script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python main.py
